services:
  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: telegram-bot-hackaton-example
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
