"""Add Attraction table

Revision ID: e3f3549ce746
Revises: 5059da10ba2b
Create Date: 2024-10-31 01:12:11.082503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3f3549ce746"
down_revision: Union[str, None] = "5059da10ba2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("tsv_description", postgresql.TSVECTOR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attractions_tsv_description",
        "attractions",
        ["tsv_description"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_attractions_tsv_description", table_name="attractions", postgresql_using="gin"
    )
    op.drop_table("attractions")
    # ### end Alembic commands ###
