"""initial

Revision ID: cf35e08873f2
Revises: 
Create Date: 2024-10-30 13:55:07.716688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf35e08873f2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.alter_column("users", "firstname", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("users", "surname", existing_type=sa.VARCHAR(length=64), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "surname", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column("users", "firstname", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.drop_column("users", "context")
    # ### end Alembic commands ###
